param(
    [string]$ProjectRoot = "",
    [switch]$Quiet
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# 去掉首尾空白与尾部 \、/（cmd 传入 "%~dp0" 时末尾反斜杠会破坏 PowerShell 对 -ProjectRoot "..." 的解析）
if (-not [string]::IsNullOrWhiteSpace($ProjectRoot)) {
    $ProjectRoot = $ProjectRoot.Trim().TrimEnd([char[]]@('\', '/'))
}
if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
    $ProjectRoot = Join-Path $PSScriptRoot ".."
}

$ProjectRoot = [System.IO.Path]::GetFullPath($ProjectRoot)
$dateDir = Join-Path $ProjectRoot "date"

function Load-CsvRows([string]$fileName) {
    $path = Join-Path $dateDir $fileName
    if (-not (Test-Path $path)) {
        throw "CSV not found: $path"
    }
    return @(Import-Csv -Path $path -Encoding UTF8)
}

if (-not (Test-Path $dateDir)) {
    throw "Date directory not found: $dateDir"
}

# 0) merchants.csv -> city-coords.json
$coordScript = Join-Path $PSScriptRoot "sync-city-coords.ps1"
if (Test-Path $coordScript) {
    & $coordScript -ProjectRoot $ProjectRoot -Quiet
}

# 1) CSV -> datasets.data.js
$datasetConfig = @(
    @{ key = "dynamic"; csv = "dynamic.csv" },
    @{ key = "demand"; csv = "demand.csv" },
    @{ key = "coreServices"; csv = "core_services.csv" },
    @{ key = "industry"; csv = "industry.csv" },
    @{ key = "cultureStories"; csv = "culture_stories.csv" },
    @{ key = "industryProfiles"; csv = "industry_profiles.csv" },
    @{ key = "merchants"; csv = "merchants.csv" },
    @{ key = "mapCities"; csv = "map_cities.csv" }
)

$datasets = [ordered]@{}
foreach ($cfg in $datasetConfig) {
    $datasets[$cfg.key] = Load-CsvRows $cfg.csv
}

$datasetsJson = ConvertTo-Json -InputObject $datasets -Depth 8
$datasetsContent = @(
    "// Auto generated by scripts/sync-data.ps1",
    "window.APP_DATASETS = $datasetsJson;"
) -join "`r`n"
Set-Content -Path (Join-Path $dateDir "datasets.data.js") -Value $datasetsContent -Encoding UTF8

if (-not $Quiet) {
    Write-Host "[OK] Sync completed:" -ForegroundColor Green
    Write-Host " - date/datasets.data.js" -ForegroundColor Cyan
}
